version: '3'

services:

  #  start Redis, and ensure that data is stored to a mounted volume
  redis:
    image: 'redis:alpine'
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data
